//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace File_Transfer.LanguageManager.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_tr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_tr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("File_Transfer.LanguageManager.Languages.Lang_tr", typeof(Lang_tr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Transfer.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Bekle....
        /// </summary>
        internal static string btnReceiveFile {
            get {
                return ResourceManager.GetString("btnReceiveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Seç.
        /// </summary>
        internal static string btnSelectFile {
            get {
                return ResourceManager.GetString("btnSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Yeri Seç.
        /// </summary>
        internal static string btnSelectSaveLocation {
            get {
                return ResourceManager.GetString("btnSelectSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosyayı Gönder.
        /// </summary>
        internal static string btnSendFile {
            get {
                return ResourceManager.GetString("btnSendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göndermeyi İptal Et.
        /// </summary>
        internal static string CancelSending {
            get {
                return ResourceManager.GetString("CancelSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferi İptal Et.
        /// </summary>
        internal static string CancelTransfer {
            get {
                return ResourceManager.GetString("CancelTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beklemeyi İptal Et.
        /// </summary>
        internal static string CancelWaiting {
            get {
                return ResourceManager.GetString("CancelWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya İsteği Geldi.
        /// </summary>
        internal static string FileRequestHasCame {
            get {
                return ResourceManager.GetString("FileRequestHasCame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya isteği geldi, kullanıcıdan yanıt bekleniyor....
        /// </summary>
        internal static string FileRequestJustComeUpWaitingUserResponse {
            get {
                return ResourceManager.GetString("FileRequestJustComeUpWaitingUserResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Gönderiliyor....
        /// </summary>
        internal static string FileSending {
            get {
                return ResourceManager.GetString("FileSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Bekleme İptal Edildi.
        /// </summary>
        internal static string FileWaitingWasCancelled {
            get {
                return ResourceManager.GetString("FileWaitingWasCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Transfer Uygulaması Hakkında.
        /// </summary>
        internal static string GroupBoxAboutApp {
            get {
                return ResourceManager.GetString("GroupBoxAboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geliştirici Hakkında.
        /// </summary>
        internal static string GroupBoxAboutDeveloper {
            get {
                return ResourceManager.GetString("GroupBoxAboutDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir dosya seçiniz..
        /// </summary>
        internal static string InvalidFilenameMessage {
            get {
                return ResourceManager.GetString("InvalidFilenameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz Dosya.
        /// </summary>
        internal static string InvalidFilenameMessageTitle {
            get {
                return ResourceManager.GetString("InvalidFilenameMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen girdiğiniz bilgileri kontrol ediniz..
        /// </summary>
        internal static string InvalidFormInputMessage {
            get {
                return ResourceManager.GetString("InvalidFormInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz Veri Girişi.
        /// </summary>
        internal static string InvalidFormInputMessageTitle {
            get {
                return ResourceManager.GetString("InvalidFormInputMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir IP adresi giriniz..
        /// </summary>
        internal static string InvalidIpAddressMessage {
            get {
                return ResourceManager.GetString("InvalidIpAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz IP Adresi.
        /// </summary>
        internal static string InvalidIpAddressMessageTitle {
            get {
                return ResourceManager.GetString("InvalidIpAddressMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir port numarası giriniz..
        /// </summary>
        internal static string InvalidPortNumberMessage {
            get {
                return ResourceManager.GetString("InvalidPortNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz Port Numarası.
        /// </summary>
        internal static string InvalidPortNumberMessageTitle {
            get {
                return ResourceManager.GetString("InvalidPortNumberMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir kayıt dizini seçiniz..
        /// </summary>
        internal static string InvalidSaveLocationMessage {
            get {
                return ResourceManager.GetString("InvalidSaveLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz Kayıt Dizini.
        /// </summary>
        internal static string InvalidSaveLocationMessageTitle {
            get {
                return ResourceManager.GetString("InvalidSaveLocationMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © {0} {1} - Tüm Hakları Saklıdır.
        /// </summary>
        internal static string labelAllRightReserved {
            get {
                return ResourceManager.GetString("labelAllRightReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Github Repository.
        /// </summary>
        internal static string labelAppGithubRepository {
            get {
                return ResourceManager.GetString("labelAppGithubRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Versiyon {1}.
        /// </summary>
        internal static string labelAppNameAndVersion {
            get {
                return ResourceManager.GetString("labelAppNameAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geliştirici Github Profili: @FiratEski.
        /// </summary>
        internal static string labelDeveloperGithubProfile {
            get {
                return ResourceManager.GetString("labelDeveloperGithubProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fırat Eşki / @firateski / firateski@outlook.com.
        /// </summary>
        internal static string labelDeveloperName {
            get {
                return ResourceManager.GetString("labelDeveloperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geliştirici Web Sitesi: FiratEski.com.
        /// </summary>
        internal static string labelDeveloperWebSite {
            get {
                return ResourceManager.GetString("labelDeveloperWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya.
        /// </summary>
        internal static string labelFileLocation {
            get {
                return ResourceManager.GetString("labelFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Adresi.
        /// </summary>
        internal static string labelReceiverIPAdress {
            get {
                return ResourceManager.GetString("labelReceiverIPAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string labelReceiverPort {
            get {
                return ResourceManager.GetString("labelReceiverPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Yeri.
        /// </summary>
        internal static string labelSaveLocation {
            get {
                return ResourceManager.GetString("labelSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Adresi.
        /// </summary>
        internal static string labelSenderIPAdress {
            get {
                return ResourceManager.GetString("labelSenderIPAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string labelSenderPort {
            get {
                return ResourceManager.GetString("labelSenderPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Transfer.
        /// </summary>
        internal static string MainView {
            get {
                return ResourceManager.GetString("MainView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; ismindeki {1} boyutundaki dosyayı almak istiyor musunuz?.
        /// </summary>
        internal static string ReceiverAskForReceiveFile {
            get {
                return ResourceManager.GetString("ReceiverAskForReceiveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya alınsın mı?.
        /// </summary>
        internal static string ReceiverAskForReceiveFileTitle {
            get {
                return ResourceManager.GetString("ReceiverAskForReceiveFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya alımı kullanıcı tarafından iptal edildi..
        /// </summary>
        internal static string ReceiverCancelledByUser {
            get {
                return ResourceManager.GetString("ReceiverCancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem İptal Edildi.
        /// </summary>
        internal static string ReceiverCancelledByUserTitle {
            get {
                return ResourceManager.GetString("ReceiverCancelledByUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya başarıyla alındı..
        /// </summary>
        internal static string ReceiverCompleted {
            get {
                return ResourceManager.GetString("ReceiverCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Tamamlandı.
        /// </summary>
        internal static string ReceiverCompletedTitle {
            get {
                return ResourceManager.GetString("ReceiverCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akıştan veri okunamadığı için dosya alınamadı..
        /// </summary>
        internal static string ReceiverCouldntReadStream {
            get {
                return ResourceManager.GetString("ReceiverCouldntReadStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri Okuma Hatası.
        /// </summary>
        internal static string ReceiverCouldntReadStreamTitle {
            get {
                return ResourceManager.GetString("ReceiverCouldntReadStreamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya alınırken bilinmeyen bir sorun oluştu:
        ///
        ///{0}.
        /// </summary>
        internal static string ReceiverException {
            get {
                return ResourceManager.GetString("ReceiverException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beklenmeyen Bir Hata Oluştu.
        /// </summary>
        internal static string ReceiverExceptionTitle {
            get {
                return ResourceManager.GetString("ReceiverExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karşı taraf bağlantıyı iptal ettiği için veya bağlantı koptuğu için dosya alınamadı..
        /// </summary>
        internal static string ReceiverFailed {
            get {
                return ResourceManager.GetString("ReceiverFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Tamamlanamadı.
        /// </summary>
        internal static string ReceiverFailedTitle {
            get {
                return ResourceManager.GetString("ReceiverFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya alımını kabul etmediğiniz için dosya alımı iptal edildi..
        /// </summary>
        internal static string ReceiverFileRejectedByUser {
            get {
                return ResourceManager.GetString("ReceiverFileRejectedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem İptal Edildi!.
        /// </summary>
        internal static string ReceiverFileRejectedByUserTitle {
            get {
                return ResourceManager.GetString("ReceiverFileRejectedByUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt dizininden veya başka bir nedenden dolayı G/Ç hatası meydana geldiği için dosya alınamadı..
        /// </summary>
        internal static string ReceiverIOException {
            get {
                return ResourceManager.GetString("ReceiverIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karşı taraf bağlantıyı iptal ettiği için veya bağlantı koptuğu için dosya gönderilemedi..
        /// </summary>
        internal static string ReceiverIOException10054 {
            get {
                return ResourceManager.GetString("ReceiverIOException10054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Gönderilemedi.
        /// </summary>
        internal static string ReceiverIOException10054Title {
            get {
                return ResourceManager.GetString("ReceiverIOException10054Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G/Ç Hatası.
        /// </summary>
        internal static string ReceiverIOExceptionTitle {
            get {
                return ResourceManager.GetString("ReceiverIOExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saniye.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderme parametrelerinde meydana gelen sorundan dolayı gönderme işlemi yapılamıyor. Lütfen Ayarlarınızı gözden geçirip programı yeniden başlattıktan sonra işleminizi tekrarlayın..
        /// </summary>
        internal static string SenderArgumentException {
            get {
                return ResourceManager.GetString("SenderArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argüman Hatası.
        /// </summary>
        internal static string SenderArgumentExceptionTitle {
            get {
                return ResourceManager.GetString("SenderArgumentExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderme parametrelerinde geçersiz parametreden dolayı gönderme işlemi yapılamıyor. Lütfen Ayarlarınızı gözden geçirip programı yeniden başlattıktan sonra işleminizi tekrarlayın..
        /// </summary>
        internal static string SenderArgumentNullException {
            get {
                return ResourceManager.GetString("SenderArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz Argüman Hatası.
        /// </summary>
        internal static string SenderArgumentNullExceptionTitle {
            get {
                return ResourceManager.GetString("SenderArgumentNullExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya gönderme kullanıcı tarafından iptal edildi..
        /// </summary>
        internal static string SenderCancelledByUser {
            get {
                return ResourceManager.GetString("SenderCancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem İptal Edildi.
        /// </summary>
        internal static string SenderCancelledByUserTitle {
            get {
                return ResourceManager.GetString("SenderCancelledByUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya başarıyla gönderildi..
        /// </summary>
        internal static string SenderCompleted {
            get {
                return ResourceManager.GetString("SenderCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Tamamlandı.
        /// </summary>
        internal static string SenderCompletedTitle {
            get {
                return ResourceManager.GetString("SenderCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstenilen IP adresiyle bağlantı sağlanamadı. Olası nedenler:
        ///
        ///1- Karşıdaki kullanıcı dosya bekleme moduna geçmemiş olabilir.
        ///2- IP adresi veya port numarası eşleşmemiş olabilir.
        ///3- Karşıdaki kullanıcı gerekli port yapılandırmasını yapmamış olabilir.
        ///4- İnternet bağlantınız veya karşı tarafın internet bağlantısı olmayabilir..
        /// </summary>
        internal static string SenderConnectError {
            get {
                return ResourceManager.GetString("SenderConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantı Hatası.
        /// </summary>
        internal static string SenderConnectErrorTitle {
            get {
                return ResourceManager.GetString("SenderConnectErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akışa veri yazılamadığı için dosya gönderilemedi..
        /// </summary>
        internal static string SenderCouldntWriteToStream {
            get {
                return ResourceManager.GetString("SenderCouldntWriteToStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri Yazma Hatası.
        /// </summary>
        internal static string SenderCouldntWriteToStreamTitle {
            get {
                return ResourceManager.GetString("SenderCouldntWriteToStreamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belirtilen dizin bulunamadı. Lütfen geçerli bir dosya seçtiğinize emin olun..
        /// </summary>
        internal static string SenderDirectoryNotFoundException {
            get {
                return ResourceManager.GetString("SenderDirectoryNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz Dizin Hatası.
        /// </summary>
        internal static string SenderDirectoryNotFoundExceptionTitle {
            get {
                return ResourceManager.GetString("SenderDirectoryNotFoundExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya gönderilirken bilinmeyen bir hata oluştu:
        ///
        ///{0}.
        /// </summary>
        internal static string SenderException {
            get {
                return ResourceManager.GetString("SenderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beklenmeyen Bir Hata Oluştu.
        /// </summary>
        internal static string SenderExceptionTitle {
            get {
                return ResourceManager.GetString("SenderExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya gönderilirken hata oluştu..
        /// </summary>
        internal static string SenderFailed {
            get {
                return ResourceManager.GetString("SenderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Gönderme Hatası.
        /// </summary>
        internal static string SenderFailedTitle {
            get {
                return ResourceManager.GetString("SenderFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz dosya bulunamadığından veya dosyayı okuma izni olmadığından dolayı G/Ç hatası meydana geldi ve dosya gönderilemedi..
        /// </summary>
        internal static string SenderIOException {
            get {
                return ResourceManager.GetString("SenderIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karşı taraf bağlantıyı iptal ettiği için veya bağlantı koptuğu için dosya gönderilemedi..
        /// </summary>
        internal static string SenderIOExceptionError10054 {
            get {
                return ResourceManager.GetString("SenderIOExceptionError10054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantı Hatası.
        /// </summary>
        internal static string SenderIOExceptionError10054Title {
            get {
                return ResourceManager.GetString("SenderIOExceptionError10054Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G/Ç Hatası.
        /// </summary>
        internal static string SenderIOExceptionTitle {
            get {
                return ResourceManager.GetString("SenderIOExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya yolu çok uzun olduğu için dosya gönderme işlemine başlanamadı. Lütfen daha kısa bir yol ile yeniden deneyin..
        /// </summary>
        internal static string SenderPathTooLongException {
            get {
                return ResourceManager.GetString("SenderPathTooLongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Yolu Hatası.
        /// </summary>
        internal static string SenderPathTooLongExceptionTitle {
            get {
                return ResourceManager.GetString("SenderPathTooLongExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerekli yetkiler bulunmadığı için dosya gönderilemedi. Programı yönetici olarak çalıştırıp tekrar göndermeyi deneyin..
        /// </summary>
        internal static string SenderUnauthorizedAccessException {
            get {
                return ResourceManager.GetString("SenderUnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenlikten Kaynaklı Hata.
        /// </summary>
        internal static string SenderUnauthorizedAccessExceptionTitle {
            get {
                return ResourceManager.GetString("SenderUnauthorizedAccessExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkında.
        /// </summary>
        internal static string TabPageAbout {
            get {
                return ResourceManager.GetString("TabPageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Al.
        /// </summary>
        internal static string TabPageReceiver {
            get {
                return ResourceManager.GetString("TabPageReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Gönder.
        /// </summary>
        internal static string TabPageSender {
            get {
                return ResourceManager.GetString("TabPageSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya seçmek için tıklayın....
        /// </summary>
        internal static string txtFileLocation {
            get {
                return ResourceManager.GetString("txtFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt yeri seçmek için tıklayın....
        /// </summary>
        internal static string txtSaveLocation {
            get {
                return ResourceManager.GetString("txtSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Bekleniyor....
        /// </summary>
        internal static string WaitingForFile {
            get {
                return ResourceManager.GetString("WaitingForFile", resourceCulture);
            }
        }
    }
}
