//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace File_Transfer.LanguageManager.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("File_Transfer.LanguageManager.Languages.Lang_en", typeof(Lang_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Transfer.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for File....
        /// </summary>
        internal static string btnReceiveFile {
            get {
                return ResourceManager.GetString("btnReceiveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        internal static string btnSelectFile {
            get {
                return ResourceManager.GetString("btnSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        internal static string btnSelectSaveLocation {
            get {
                return ResourceManager.GetString("btnSelectSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send File.
        /// </summary>
        internal static string btnSendFile {
            get {
                return ResourceManager.GetString("btnSendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Sending.
        /// </summary>
        internal static string CancelSending {
            get {
                return ResourceManager.GetString("CancelSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the Transfer.
        /// </summary>
        internal static string CancelTransfer {
            get {
                return ResourceManager.GetString("CancelTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Waiting.
        /// </summary>
        internal static string CancelWaiting {
            get {
                return ResourceManager.GetString("CancelWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Request Has Came.
        /// </summary>
        internal static string FileRequestHasCame {
            get {
                return ResourceManager.GetString("FileRequestHasCame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File request just came up, waiting user response....
        /// </summary>
        internal static string FileRequestJustComeUpWaitingUserResponse {
            get {
                return ResourceManager.GetString("FileRequestJustComeUpWaitingUserResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Being Sending....
        /// </summary>
        internal static string FileSending {
            get {
                return ResourceManager.GetString("FileSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Waiting Was Cancelled by User.
        /// </summary>
        internal static string FileWaitingWasCancelled {
            get {
                return ResourceManager.GetString("FileWaitingWasCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About File Transfer App.
        /// </summary>
        internal static string GroupBoxAboutApp {
            get {
                return ResourceManager.GetString("GroupBoxAboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Developer.
        /// </summary>
        internal static string GroupBoxAboutDeveloper {
            get {
                return ResourceManager.GetString("GroupBoxAboutDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid file..
        /// </summary>
        internal static string InvalidFilenameMessage {
            get {
                return ResourceManager.GetString("InvalidFilenameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File.
        /// </summary>
        internal static string InvalidFilenameMessageTitle {
            get {
                return ResourceManager.GetString("InvalidFilenameMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the data you have entered on the form..
        /// </summary>
        internal static string InvalidFormInputMessage {
            get {
                return ResourceManager.GetString("InvalidFormInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data Entry.
        /// </summary>
        internal static string InvalidFormInputMessageTitle {
            get {
                return ResourceManager.GetString("InvalidFormInputMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid IP address..
        /// </summary>
        internal static string InvalidIpAddressMessage {
            get {
                return ResourceManager.GetString("InvalidIpAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP Address.
        /// </summary>
        internal static string InvalidIpAddressMessageTitle {
            get {
                return ResourceManager.GetString("InvalidIpAddressMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid port number..
        /// </summary>
        internal static string InvalidPortNumberMessage {
            get {
                return ResourceManager.GetString("InvalidPortNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Port Number.
        /// </summary>
        internal static string InvalidPortNumberMessageTitle {
            get {
                return ResourceManager.GetString("InvalidPortNumberMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid save location..
        /// </summary>
        internal static string InvalidSaveLocationMessage {
            get {
                return ResourceManager.GetString("InvalidSaveLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Save Location.
        /// </summary>
        internal static string InvalidSaveLocationMessageTitle {
            get {
                return ResourceManager.GetString("InvalidSaveLocationMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © {0} {1} - All Right Reserved.
        /// </summary>
        internal static string labelAllRightReserved {
            get {
                return ResourceManager.GetString("labelAllRightReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Github Repository.
        /// </summary>
        internal static string labelAppGithubRepository {
            get {
                return ResourceManager.GetString("labelAppGithubRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Version {1}.
        /// </summary>
        internal static string labelAppNameAndVersion {
            get {
                return ResourceManager.GetString("labelAppNameAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Github Profile: @FiratEski.
        /// </summary>
        internal static string labelDeveloperGithubProfile {
            get {
                return ResourceManager.GetString("labelDeveloperGithubProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firat Eski / @firateski / firateski@outlook.com.
        /// </summary>
        internal static string labelDeveloperName {
            get {
                return ResourceManager.GetString("labelDeveloperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Website: FiratEski.com.
        /// </summary>
        internal static string labelDeveloperWebSite {
            get {
                return ResourceManager.GetString("labelDeveloperWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string labelFileLocation {
            get {
                return ResourceManager.GetString("labelFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string labelReceiverIPAdress {
            get {
                return ResourceManager.GetString("labelReceiverIPAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string labelReceiverPort {
            get {
                return ResourceManager.GetString("labelReceiverPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Location.
        /// </summary>
        internal static string labelSaveLocation {
            get {
                return ResourceManager.GetString("labelSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string labelSenderIPAdress {
            get {
                return ResourceManager.GetString("labelSenderIPAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string labelSenderPort {
            get {
                return ResourceManager.GetString("labelSenderPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Transfer.
        /// </summary>
        internal static string MainView {
            get {
                return ResourceManager.GetString("MainView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to receive the file &quot;{0}&quot; which is {1} in size?.
        /// </summary>
        internal static string ReceiverAskForReceiveFile {
            get {
                return ResourceManager.GetString("ReceiverAskForReceiveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want to Receive The File?.
        /// </summary>
        internal static string ReceiverAskForReceiveFileTitle {
            get {
                return ResourceManager.GetString("ReceiverAskForReceiveFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file receiving cancelled by user..
        /// </summary>
        internal static string ReceiverCancelledByUser {
            get {
                return ResourceManager.GetString("ReceiverCancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Cancelled.
        /// </summary>
        internal static string ReceiverCancelledByUserTitle {
            get {
                return ResourceManager.GetString("ReceiverCancelledByUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file received successfully..
        /// </summary>
        internal static string ReceiverCompleted {
            get {
                return ResourceManager.GetString("ReceiverCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Completed.
        /// </summary>
        internal static string ReceiverCompletedTitle {
            get {
                return ResourceManager.GetString("ReceiverCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be received because the data could not be read from the stream..
        /// </summary>
        internal static string ReceiverCouldntReadStream {
            get {
                return ResourceManager.GetString("ReceiverCouldntReadStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Read Error.
        /// </summary>
        internal static string ReceiverCouldntReadStreamTitle {
            get {
                return ResourceManager.GetString("ReceiverCouldntReadStreamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred while receiving the file:
        ///
        ///{0}.
        /// </summary>
        internal static string ReceiverException {
            get {
                return ResourceManager.GetString("ReceiverException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        internal static string ReceiverExceptionTitle {
            get {
                return ResourceManager.GetString("ReceiverExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file couldn&apos;t be received due to that either the remote user cancelled or the connection is lost..
        /// </summary>
        internal static string ReceiverFailed {
            get {
                return ResourceManager.GetString("ReceiverFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Failed.
        /// </summary>
        internal static string ReceiverFailedTitle {
            get {
                return ResourceManager.GetString("ReceiverFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File receiving was cancelled at your request..
        /// </summary>
        internal static string ReceiverFileRejectedByUser {
            get {
                return ResourceManager.GetString("ReceiverFileRejectedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Cancelled.
        /// </summary>
        internal static string ReceiverFileRejectedByUserTitle {
            get {
                return ResourceManager.GetString("ReceiverFileRejectedByUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file couldn&apos;t be received due to I/O error which is can cause the invalid save location or other write exceptions..
        /// </summary>
        internal static string ReceiverIOException {
            get {
                return ResourceManager.GetString("ReceiverIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file couldn&apos;t be sent due to either the remote user cancelled or the connection lost..
        /// </summary>
        internal static string ReceiverIOException10054 {
            get {
                return ResourceManager.GetString("ReceiverIOException10054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File Could Not Send.
        /// </summary>
        internal static string ReceiverIOException10054Title {
            get {
                return ResourceManager.GetString("ReceiverIOException10054Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/O Error.
        /// </summary>
        internal static string ReceiverIOExceptionTitle {
            get {
                return ResourceManager.GetString("ReceiverIOExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be sent due to the error that occurred in the sender argument. Please try again after resetting your settings and restarting the application..
        /// </summary>
        internal static string SenderArgumentException {
            get {
                return ResourceManager.GetString("SenderArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument Exception.
        /// </summary>
        internal static string SenderArgumentExceptionTitle {
            get {
                return ResourceManager.GetString("SenderArgumentExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be sent because of the invalid argument of sender. Please try again after resetting your settings and restarting the application..
        /// </summary>
        internal static string SenderArgumentNullException {
            get {
                return ResourceManager.GetString("SenderArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument Invalid Exception.
        /// </summary>
        internal static string SenderArgumentNullExceptionTitle {
            get {
                return ResourceManager.GetString("SenderArgumentNullExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file sending was cancelled at your request..
        /// </summary>
        internal static string SenderCancelledByUser {
            get {
                return ResourceManager.GetString("SenderCancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Operation Cancelled.
        /// </summary>
        internal static string SenderCancelledByUserTitle {
            get {
                return ResourceManager.GetString("SenderCancelledByUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file sent successfully..
        /// </summary>
        internal static string SenderCompleted {
            get {
                return ResourceManager.GetString("SenderCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Operation Completed.
        /// </summary>
        internal static string SenderCompletedTitle {
            get {
                return ResourceManager.GetString("SenderCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to IP address due to the one of the following reasons:
        ///
        ///1- The remote user did not switch the program to the file wait mode.
        ///2- The IP address or port number wasn&apos;t match with the remote user.
        ///3- The remote user did not configure the port forwarding.
        ///4- You or remote user have no internet connection..
        /// </summary>
        internal static string SenderConnectError {
            get {
                return ResourceManager.GetString("SenderConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        internal static string SenderConnectErrorTitle {
            get {
                return ResourceManager.GetString("SenderConnectErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be sent due to cannot write data to the stream..
        /// </summary>
        internal static string SenderCouldntWriteToStream {
            get {
                return ResourceManager.GetString("SenderCouldntWriteToStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Write Error.
        /// </summary>
        internal static string SenderCouldntWriteToStreamTitle {
            get {
                return ResourceManager.GetString("SenderCouldntWriteToStreamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory you specified could not be found. Please make sure you select a valid save path..
        /// </summary>
        internal static string SenderDirectoryNotFoundException {
            get {
                return ResourceManager.GetString("SenderDirectoryNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Not Found Exception.
        /// </summary>
        internal static string SenderDirectoryNotFoundExceptionTitle {
            get {
                return ResourceManager.GetString("SenderDirectoryNotFoundExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while sending file:
        ///
        ///{0}.
        /// </summary>
        internal static string SenderException {
            get {
                return ResourceManager.GetString("SenderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error Occurred.
        /// </summary>
        internal static string SenderExceptionTitle {
            get {
                return ResourceManager.GetString("SenderExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while sending file..
        /// </summary>
        internal static string SenderFailed {
            get {
                return ResourceManager.GetString("SenderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Send Failed.
        /// </summary>
        internal static string SenderFailedTitle {
            get {
                return ResourceManager.GetString("SenderFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file couldn&apos;t be sent due to I/O error which is can cause the invalid file location or other read exceptions..
        /// </summary>
        internal static string SenderIOException {
            get {
                return ResourceManager.GetString("SenderIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file couldn&apos;t be sent due to that either the remote user cancelled or the connection is lost..
        /// </summary>
        internal static string SenderIOExceptionError10054 {
            get {
                return ResourceManager.GetString("SenderIOExceptionError10054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        internal static string SenderIOExceptionError10054Title {
            get {
                return ResourceManager.GetString("SenderIOExceptionError10054Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/O Error.
        /// </summary>
        internal static string SenderIOExceptionTitle {
            get {
                return ResourceManager.GetString("SenderIOExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file sending couldn&apos;t be started due to selected path is too long. Please select a shorter path and try again..
        /// </summary>
        internal static string SenderPathTooLongException {
            get {
                return ResourceManager.GetString("SenderPathTooLongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Too Long Exception.
        /// </summary>
        internal static string SenderPathTooLongExceptionTitle {
            get {
                return ResourceManager.GetString("SenderPathTooLongExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file couldn&apos;t be sent due to the unauthorized exception which can prevent the file to being read. Please try again after restarting the application with administrator privileges..
        /// </summary>
        internal static string SenderUnauthorizedAccessException {
            get {
                return ResourceManager.GetString("SenderUnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Exception.
        /// </summary>
        internal static string SenderUnauthorizedAccessExceptionTitle {
            get {
                return ResourceManager.GetString("SenderUnauthorizedAccessExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string TabPageAbout {
            get {
                return ResourceManager.GetString("TabPageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive File.
        /// </summary>
        internal static string TabPageReceiver {
            get {
                return ResourceManager.GetString("TabPageReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send File.
        /// </summary>
        internal static string TabPageSender {
            get {
                return ResourceManager.GetString("TabPageSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select file....
        /// </summary>
        internal static string txtFileLocation {
            get {
                return ResourceManager.GetString("txtFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select save location....
        /// </summary>
        internal static string txtSaveLocation {
            get {
                return ResourceManager.GetString("txtSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for File....
        /// </summary>
        internal static string WaitingForFile {
            get {
                return ResourceManager.GetString("WaitingForFile", resourceCulture);
            }
        }
    }
}
